- engine/api.py
- engine/checker/checker.cu
- src/pages/problems/[slug].tsx
Rewrote api.py for brevity and using a generic for every modal endpoint. Now, can make changes without having to change it in every single endpoint.
Updated both checker and benchmark to stream using a Pipe. Everything that is written to stdout gets streamed as an event.
Also, updated the UI to only display a progress bar when running tests. After that, display the benchmarking results. All happening in real.
**BEFORE**:
No progress bar, this is displayed until all test cases are run
After test cases are done, no real time benchmarking, this is displayed until all benchmarks are done
**AFTER**:
> Feature: streaming for testing and benchmarking

- public/content/tensara-score.md
- src/components/layout/header/index.tsx
- src/pages/[username].tsx
- src/pages/blog/index.tsx
- src/pages/blog/tensara-score.tsx
- src/pages/leaderboard/index.tsx
- src/server/api/root.ts
- src/server/api/routers/submissions.ts
- src/server/api/routers/users.ts
- src/server/auth/config.ts
Has these features:
- Activity Grid
- Recent submissions
- Implementation of Tensara Score algorithm
- Blog Post explaining how the Tensara Score algorithm works
> Make profile page

- src/constants/gpu.ts
- src/constants/language.ts
- src/pages/problems/[slug].tsx
- src/pages/submissions/[id].tsx
- src/pages/submissions/index.tsx
- src/server/api/routers/problems.ts
- src/types/problem.ts
- my submissions page now has language (you can also filter/sort) + fixed filtering for other fields
- add wrong answer debug info for view submission 
- the submission list in [slug].tsx now shows language too + fixed margins/error icon
> frontend fixes (2)

- engine/archive/device_query.py
- src/components/GpuInfoModal.tsx
- src/components/LanguageInfoModal.tsx
- src/constants/deviceQuery.ts
- src/constants/gpu.ts
- src/pages/problems/[slug].tsx
this is the most manual labor ive ever done but for every GPU, it shows important info from `deviceQuery` + triton/cuda versions
> GPU + Compiler Info

- src/components/layout/index.tsx
- src/pages/index.tsx
Changes the "CUDA code" to "GPU kernels" since we have triton now
> update since we have triton now

- src/constants/gpu.ts
- src/constants/language.ts
- src/pages/[username].tsx
- src/server/api/routers/users.ts
- src/styles/globals.css
> Profile page

- .github/workflows/pr-build.yml
- engine/api.py
- engine/problem.py
- engine/pyproject.toml
- engine/runner.py
- engine/utils.py
- engine/uv.lock
Run the binary_runner function inside a subprocess, with timeout on the queue get. Tested works
> run problems in a subprocess

- public/content/benchmarking.md
- src/pages/blog/benchmarking.tsx
Outlined our benchmarking process
> Add benchmarking blog

- src/components/layout/AppLayout.tsx
- src/pages/_app.tsx
> Smooth transition

- src/pages/leaderboard/index.tsx
Doesn't get nuked when opened on phone
> Added mobile view for leaderboard

- src/components/profile/ActivityCalendar.tsx
- src/server/api/routers/users.ts
> Profile fix, UI

- engine/api.py
- engine/utils.py
> Allow inf values to be displayed

- src/components/problem/SubmissionForm.tsx
- src/constants/gpu.ts
- src/pages/leaderboard/[slug].tsx
- src/pages/leaderboard/index.tsx
- src/pages/problems/index.tsx
- src/pages/submissions/index.tsx
> fix: native dropdown

- src/components/problem/MySubmissions.tsx
- src/constants/problem.ts
for #70 
- added filter by status and sort by fastest/newest
- for mobile/smaller screens, the button select for status should shrink to a filter button w dropdown
> in-problem submission filters

- src/pages/leaderboard/[slug].tsx
- src/pages/leaderboard/index.tsx
- src/pages/submissions/[id].tsx
- src/pages/submissions/index.tsx
#65 
- problem name in my submission is white now, not blue
- rounded corners for leaderboard
- added links to problem page to both index and problem specific leaderboard
> feat: problem links in leaderboard

- package.json
- pnpm-lock.yaml
- src/components/misc/GpuInfoModal.tsx
- src/components/misc/LanguageInfoModal.tsx
- src/components/problem/ProblemView.tsx
- src/components/problem/SubmissionForm.tsx
- src/components/problem/SubmissionResults.tsx
- src/components/profile/ActivityCalendar.tsx
- src/constants/problem.ts
- src/pages/api/submissions/direct-submit.ts
- src/pages/leaderboard/[slug].tsx
- src/pages/leaderboard/index.tsx
- src/pages/problems/[slug].tsx
- src/pages/problems/index.tsx
- src/pages/submissions/[id].tsx
- src/pages/submissions/index.tsx
- switched over from chakra-ui icons to react-icons
- added copy button #52
- for WA, we still had total tests = passed tests, fixed that
> icons + copy button

- src/components/layout/header/index.tsx
- src/components/problem/MySubmissions.tsx
- src/components/problem/SubmissionForm.tsx
- src/pages/leaderboard/[slug].tsx
- src/pages/leaderboard/index.tsx
- src/pages/problems/index.tsx
- src/pages/submissions/index.tsx
- show indication of submission being public or not #77 
- added transition animation on hover for navbar 
- leaderboard view selection is saved in local storage
- replaced `Leaderboard > [Name]` with `[Name] [Icon]` on problem-specific leaderboards
> more UI tweaks

- src/components/problem/CodeEditor.tsx
- src/pages/submissions/[id].tsx
- fixed mojo color scheme (comment tokenizer) 
- `CodeEditor` component is used both in problem video and submission view
> editor tweaks

- src/pages/cli/index.tsx
- src/pages/index.tsx
- better entrypoint on the landing page:
- add copy transition to checkmark when clicked
- fixed button colors
> small ui tweaks

- src/pages/problems/index.tsx
> default problem sorting

- src/server/api/routers/users.ts
tested and worked
Package json unchanged
> Fix: issue #107, case insensitive Github usernames

- .github/workflows/ruff-lint.yml
- engine/api.py
- engine/baseline.py
- engine/problem.py
- engine/runner.py
- engine/utils.py
random bookkeeping to keep stuff clean
> add ruff linting 

- engine/api.py
need a bit of redundancy to stop submissions getting stuck in the void of `benchmarking` or `checking`
> add safeguards 

- src/components/layout/header/index.tsx
- src/pages/leaderboard/index.tsx
- src/pages/submissions/[id].tsx
we changed `tesnara.org/username` to `tensara.org/user/username` but didn't update local links
> fix profile links

- src/hooks/useSubmissionStream.ts
- src/pages/api/submissions/direct-submit.ts
#123 
adds alerts for 
- 50, 25 submissions remaining 
- <=10 submissions remaining
> rate limit warnings
